version: '3.3'

volumes:
  static_value:
  media_value:
  database:

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
#    image: rasputin21/foodgram:latest
    build: ../backend
    restart: always
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result-build/

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
