version: '3.3'
services:

  frontend:
    image: rasputin21/foodgram_frontend:latest
    volumes:
      - ./foodgram/frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./foodgram/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./foodgram/frontend/build:/usr/share/nginx/html/
      - ./foodgram/docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: rasputin21/foodgram_backend:latest
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
  database:
